// potions.ts
//

table potions_minor d100 {
	1-5:	("Potion of jump")
	6-10:	("Potion of spider climb")
	11-19:	("Potion of cure light wounds")
	20:		("Potion of love")
	21-24:	("Potion of vision")
	25-28:	("Potion of swimming")
	29-32:	("Potion of hiding")
	33-36:	("Potion of sneaking")
	37:		("Oil of timelessness")
	38-42:	("Potion of reduce (at 5th level)")
	43-47:	("Potion of enlarge (at 5th level)")
	48-50:	("Potion of speak with animals")
	51-53:	("Potion of clairaudience/clairvoyance")
	54-56:	("Potion of charisma")
	57-59:	("Potion of intelligence")
	60-62:	("Potion of wisdom")
	63-65:	("Potion of alter self")
	66-68:	("Potion of blur")
	69-71:	("Potion of darkvision")
	72-74:	("Potion of ghoul touch")
	75-77:	("Potion of delay poison")
	78-80:	("Potion of endurance")
	81-83:	("Potion of cure moderate wounds")
	84-86:	("Potion of detect thoughts")
	87-89:	("Potion of levitate")
	90-91:	("Potion of aid")
	92-93:	("Potion of invisibility")
	94:		("Potion of lesser restoration")
	95:		("Potion of cat's grace")
	96:		("Potion of bull's strength")
	97:		("Potion of truth")
	98:		("Potion of glibness")
	99:		("Potion of nondetection")
	100:	("Potion of tongues")
}

table potions_medium d100 {
	1:		("Potion of love")
	2:		("Potion of vision")
	3:		("Potion of swimming")
	4:		("Potion of hiding")
	5:		("Potion of sneaking")
	6:		("Oil of timelessness")
	7:		("Potion of reduce (at 5th level)")
	8:		("Potion of enlarge (at 5th level)")
	9:		("Potion of speak with animals")
	10:		("Potion of clairaudience/clairvoyance")
	11-12:	("Potion of charisma")
	13-14:	("Potion of intelligence")
	15-16:	("Potion of wisdom")
	17-18:	("Potion of alter self")
	19-21:	("Potion of blur")
	22-24:	("Potion of darkvision")
	25-26:	("Potion of ghoul touch")
	27-29:	("Potion of delay poison")
	30-32:	("Potion of endurance")
	33-40:	("Potion of cure moderate wounds")
	41-45:	("Potion of detect thoughts")
	46-50:	("Potion of levitate")
	51-55:	("Potion of aid")
	56-60:	("Potion of invisibility")
	61-65:	("Potion of lesser restoration")
	66-70:	("Potion of cat's grace")
	71-75:	("Potion of bull's strength")
	76-77:	("Potion of truth")
	78-79:	("Potion of glibness")
	80-84:	("Potion of nondetection")
	85-87:	("Potion of tongues")
	88-91:	("Potion of water breathing")
	92:		("Potion of remove paralysis")
	93:		("Potion of remove blindness/deafness")
	94:		("Potion of remove disease")
	95-96:	("Potion of neutralize poison")
	97:		("Potion of cure serious wounds")
	98:		("Potion of fly")
	99-100:	("Potion of heroism")
}

table potions_major d100 {
	1:		("Potion of clairaudience/clairvoyance")
	2:		("Potion of charisma")
	3:		("Potion of intelligence")
	4:		("Potion of wisdom")
	5:		("Potion of alter self")
	6-7:	("Potion of blur")
	8:		("Potion of darkvision")
	9:		("Potion of ghoul touch")
	10:		("Potion of delay poison")
	11-13:	("Potion of endurance")
	14-16:	("Potion of cure moderate wounds")
	17-19:	("Potion of detect thoughts")
	20-22:	("Potion of levitate")
	23-25:	("Potion of aid")
	26-30:	("Potion of invisibility")
	31-35:	("Potion of lesser restoration")
	36-40:	("Potion of cat's grace")
	41-45:	("Potion of bull's strength")
	46:		("Potion of truth")
	47:		("Potion of glibness")
	48-49:	("Potion of nondetection")
	50-51:	("Potion of tongues")
	52-53:	("Potion of water breathing")
	54-55:	("Potion of remove paralysis")
	56-57:	("Potion of remove blindness/deafness")
	58-59:	("Potion of remove disease")
	60-69:	("Potion of neutralize poison")
	70-73:	("Potion of cure serious wounds")
	74-75:	("Potion of fly")
	76-77:	("Potion of protection from elements (cold)")
	78-79:	("Potion of protection from elements (electricity)")
	80-83:	("Potion of protection from elements (fire)")
	84-85:	("Potion of protection from elements (acid)")
	86-87:	("Potion of protection from elements (sonic)")
	88-90:	("Potion of haste")
	91-93:	("Potion of gaseous form")
	94-95:	("Oil of slipperiness")
	96-98:	("Potion of heroism")
	99-100:	("Potion of fire breath")
}
