// wondrous.ts
//

table wondrousItems_minor d100 {
	1:		("Ioun stone (dull gray)")
	2:		("Quaal's feather token (anchor)")
	3:		("Everburning torch")
	4:		("Quaal's feather token (tree)")
	5:		("Quaal's feather token (fan)")
	6:		("Dust of tracelessness")
	7:		("Quaal's feather token (bird)")
	8:		("Quaal's feather token (swan boat)")
	9:		("Dust of illusion")
	10:		("Necklace of prayer beads (blessing)")
	11:		("Quaal's feather token (whip)")
	12:		("Scarab, golembane (flesh)")
	13:		("Bag of tricks (gray)")
	14:		("Dust of dryness")
	15:		("Bracers of armor (+1)")
	16:		("Cloak of resistance (+1)")
	17:		("Eyes of the eagle")
	18:		("Goggles of minute seeing")
	19:		("Hand of the mage")
	20:		("Pearl of power (1st-level spell)")
	21:		("Phylactery of faithfulness")
	22:		("Scarab, golembane (clay)")
	23:		("Stone of alarm")
	24:		("Pipes of the sewers")
	25:		("Scarab, golembane (stone)")
	26:		("Brooch of shielding")
	27:		("Scarab, golembane (iron)")
	28:		("Necklace of fireballs (Type I)")
	29:		("Pipes of sounding")
	30:		("Quiver of Ehlonna")
	31:		("Scarab, golembane (flesh and clay)")
	32:		("Horseshoes of speed")
	33:		("Amulet of natural armor (+1)")
	34:		("Bead of force")
	35:		("Boots of elvenkind")
	36:		("Cloak of elvenkind")
	37:		("Hat of disguise")
	38:		("Heward's handy haversack")
	39:		("Horn of fog")
	40:		("Slippers of spider climbing")
	41:		("Universal solvent")
	42:		("Vest of escape")
	43:		("Dust of appearance")
	44:		("Glove of storing")
	45:		("Sovereign glue")
	46:		("Candle of truth")
	47:		("Bag of holding (Bag 1)")
	48:		("Boots of the winterlands")
	49:		("Boots of striding and springing")
	50:		("Scarab, golembane (any golem)")
	51:		("Helm of comprehending languages and reading magic")
	52:		("Necklace of fireballs (Type II)")
	53:		("Bag of tricks (rust)")
	54:		("Chime of opening")
	55:		("Rope of climbing")
	56:		("Horseshoes of a zephyr")
	57:		("Dust of disappearance")
	58:		("Lens of detection")
	59:		("Figurine of wondrous power (silver raven)")
	60:		("Bracers of armor (+2)")
	61:		("Cloak of resistance (+2)")
	62:		("Gloves of arrow snaring")
	63:		("Ioun stone (dusty rose prism)")
	64:		("Keoghtom's ointment")
	65:		("Pearl of power (2nd-level spells)")
	66:		("Periapt of proof against poison")
	67:		("Stone salve")
	68:		("Gauntlets of ogre power")
	69:		("Bracers of health (+2)")
	70:		("Gloves of dexterity (+2)")
	71:		("Headband of intellect (+2)")
	72:		("Periapt of wisdom (+2)")
	73:		("Cloak of charisma (+2)")
	74:		("Necklace of fireballs (Type III)")
	75:		("Circlet of persuasion")
	76:		("Bracelet of friends")
	77:		("Incense of meditation")
	78:		("Bag of holding (Bag 2)")
	79:		("Ioun stone (clear spindle)")
	80:		("Necklace of prayer beads (karma)")
	81:		("Bracers of archery")
	82:		("Eversmoking bottle")
	83:		("Necklace of fireballs (Type IV)")
	84:		("Murlynd's spoon")
	85:		("Nolzur's marvelous pigments")
	86:		("Wind fan")
	87:		("Wings of flying")
	88:		("Vestment, druid's")
	89:		("Cloak of arachnida")
	90:		("Gloves of swimming and climbing")
	91:		("Horn of goodness/evil")
	92:		("Necklace of fireballs (Type V)")
	93:		("Bag of tricks (tan)")
	94:		("Circlet of blasting, minor")
	95:		("Pipes of haunting")
	96:		("Robe of useful items")
	97:		("Hand of glory")
	98:		("Bag of holding (Bag 3)")
	99-100:	("DM's choice?")
}

table wondrousItems_medium d100 {
	1:		("Boots of levitation")
	2:		("Harp of charming")
	3:		("Periapt of health")
	4:		("Candle of invocation")
	5:		("Amulet of natural armor (+2)")
	6:		("Boots of speed")
	7:		("Ioun stone (dark blue rhomboid)")
	8:		("Ioun stone (deep red sphere)")
	9:		("Ioun stone (incandescent blue sphere)")
	10:		("Ioun stone (pale blue rhomboid)")
	11:		("Ioun stone (pink rhomboid)")
	12:		("Ioun stone (pink and green sphere)")
	13:		("Ioun stone (scarlet and blue sphere)")
	14:		("Googles of night")
	15:		("Necklace of fireballs (Type VI)")
	16:		("Belt, monk's")
	17:		("Bracers of armor (+3)")
	18:		("Cloak of resistance (+3)")
	19:		("Decanter of endless water")
	20:		("Pearl of power (3rd-level spell)")
	21:		("Talisman of the sphere")
	22:		("Figurine of wondrous power (serpentine owl)")
	23:		("Necklace of fireballs (Type VII)")
	24:		("Deck of illusions")
	25:		("Boccob's blessed book")
	26:		("Bag of holding (Bag 4)")
	27:		("Figurine of wondrous power (bronze griffon)")
	28:		("Figurine of wondrous power (ebony fly)")
	29:		("Necklace of prayer beads (healing)")
	30:		("Robe of blending")
	31:		("Stone of good luck (luckstone)")
	32:		("Stone horse (courser)")
	33:		("Boat, folding")
	34:		("Amulet of undead turning")
	35:		("Gauntlet of rust")
	36:		("Boots, winged")
	37:		("Horn of blasting")
	38:		("Ioun stone (vibrant purple prism)")
	39:		("Medallion of thoughts")
	40:		("Pipes of pain")
	41:		("Cape of the mountebank")
	42:		("Lyre of building")
	43:		("Portable hole")
	44:		("Bottle of air")
	45:		("Stone horse (destrier)")
	46:		("Belt of dwarvenkind")
	47:		("Ioun stone (iridescent spindle)")
	48:		("Necklace of prayer beads (smiting)")
	49:		("Periapt of wound closure")
	50:		("Scabbard of keen edges")
	51:		("Broom of flying")
	52:		("Horn of the tritons")
	53:		("Gem of brightness")
	54:		("Pearl of the sirines")
	55:		("Figurine of wondrous power (onyx dog)")
	56:		("Chime of interruption")
	57:		("Bracers of armor (+4)")
	58:		("Cloak of resistance (+4)")
	59:		("Pearl of power (4th-level spell)")
	60:		("Belt of giant strength (+4)")
	61:		("Gloves of deterity (+4)")
	62:		("Bracers of health (+4)")
	63:		("Headband of intellect (+4)")
	64:		("Periapt of wisdom (+4)")
	65:		("Cloak of charisma (+4)")
	66:		("Figurine of wondrous power (golden lions)")
	67:		("Figurine of wondrous power (marble elephant)")
	68:		("Amulet of natural armor (+3)")
	69:		("Carpet of flying (3ft by 5ft)")
	70:		("Necklace of adaptation")
	71:		("Cloak of the manta ray")
	72:		("Ioun stone (pale green prism)")
	73:		("Ioun stone (pale lavender ellipsoid)")
	74:		("Ioun stone (pearly white spindle)")
	75:		("Figurine of wondrous power (ivory goats)")
	76:		("Rope of entanglement")
	77:		("Cube of frost resistance")
	78:		("Mattock of the titans")
	79:		("Circlet of blasting, major")
	80:		("Cloak of the bat")
	81:		("Helm of underwater action")
	82:		("Eyes of doom")
	83:		("Clock of displacement, minor (20% miss chance)")
	84:		("Clock of resistance (+5)")
	85:		("Mask of he skull")
	86:		("Maul of the titans")
	87:		("Pearl of power (5th-level spell)")
	88:		("Bracers of armor (+5)")
	89:		("Dimensional shackles")
	90:		("Iron bands of Bilarro")
	91:		("Robe of scintillating colors")
	92:		("Manual of bodily health +1")
	93:		("Manual of gainful exercise +1")
	94:		("Manual of quickness in action +1")
	95:		("Tome of clear thought +1")
	96:		("Tome of leadership and influence +1")
	97:		("Tome of understanding +1")
	98:		("Figurine of wondrous power (obsidian steed)")
	99:		("Carpet of flying (4ft by 6ft)")
	100:	("DM's choice??")
}

table wondrousItems_major d100 {
	1-2:	("Lantern of revealing")
	3-4:	("Necklace of prayer beads (wind walking)")
	5-6:	("Drums of panic")
	7-8:	("Helm of telepathy")
	9-10:	("Amulet of natural armor (+4)")
	11-12:	("Amulet of proof against detection and location")
	13-14:	("Bracers of armor (+6)")
	15:		("Belt of giant strength (+6)")
	16:		("Gloves of dexterity (+6)")
	17:		("Bracers of health (+6)")
	18:		("Headband of intellect (+6)")
	19:		("Periapt of wisdom (+6)")
	20:		("Cloak of charisma (+6)")
	21-22:	("Pearl of power (6th-level spell)")
	23-24:	("Orb of storms")
	25-26:	("Scarab of protection")
	27-28:	("Ioun stone (lavender and green ellipsoid)")
	29-30:	("Ring gates")
	31:		("Carpet of flying (5ft by 7ft)")
	32:		("Crystal ball")
	33:		("Helm of teleportation")
	34:		("Bracers of armor (+7)")
	35:		("Pearl of power (7th-level spell)")
	36:		("Amulet of natural armor (+5)")
	37:		("Cloak of displacement, major (50%% miss chance)")
	38:		("Crystal ball with detect invisibility")
	39:		("Horn of Valhalla")
	40:		("Necklace of prayer beads (summons)")
	41:		("Crystal ball with detect thoughts")
	42:		("Cloak of etherealness")
	43:		("Carpet of flying (6ft by 9ft)")
	44:		("Daern's instant fortress")
	45:		("Manual of bodily health +2")
	46:		("Manual of gainful exercise +2")
	47:		("Manual of quickness in action +2")
	48:		("Tome of clear thought +2")
	49:		("Tome of leadership and influence +2")
	50:		("Tome of understanding +2")
	51:		("Eyes of charming")
	52:		("Robe of stars")
	53:		("Darkskull")
	54:		("Cube of force")
	55:		("Bracers of armor (+8)")
	56:		("Pearl of power (8th-level spell)")
	57:		("Crystal ball with telepathy")
	58:		("Pearl of power (two spells)")
	59:		("Gem of seeing")
	60:		("Robe of the archmagi")
	61:		("Vestments of faith")
	62:		("Amulet of the planes")
	63:		("Crystal ball with true seeing")
	64:		("Pearl of power (9th-level spell)")
	65:		("Well of many worlds")
	66:		("Manual of bodily health +3")
	67:		("Manual of gainful exercise +3")
	68:		("Manual of quickness in action +3")
	69:		("Tome of clear thought +3")
	70:		("Tome of leadership and influence +3")
	71:		("Tome of understanding +3")
	72:		("Mantle of spell resistance")
	73:		("Robe of eyes")
	74:		("Mirror of opposition")
	75:		("Chaos diamond")
	76:		("Eyes of petrification")
	77:		("Bowl of commanding water elementals")
	78:		("Brazier of commanding fire elementals")
	79:		("Censer of controlling air elementals")
	80:		("Stone of controlling earth elementals")
	81:		("Manual of bodily health +4")
	82:		("Manual of gainful exercise +4")
	83:		("Manual of quickness in action +4")
	84:		("Tome of clear thought +4")
	85:		("Tome of leadership and influence +4")
	86:		("Tome of understanding +4")
	87:		("Apparatus of Kwalish")
	88:		("Manual of bodily health +5")
	89:		("Manual of gainful exercise +5")
	90:		("Manual of quickness in action +5")
	91:		("Tome of clear thought +5")
	92:		("Tome of leadership and influence +5")
	93:		("Tome of understanding +5")
	94:		("Efreeti bottle")
	95:		("Mirror of life trapping")
	96:		("Cubic gate")
	97:		("Helm of brilliance")
	98:		("Iron flask")
	99:		("Mirror of mental prowess")
	100:	("DM's choice??")
}

for i in range(1000) {
	print(wondrousItems_major());
}
